### ISSUE TITLE
ImportError: cannot import name 'QtGui' from 'PyQt4' (unknown location)

### ISSUE THREAD

**Issue by 4001982248998** [effjot/stiefogen#1]
Hi!

I would absolutely love to use this, but unfortunately it is not working on my Arch Linux system:

```
Traceback (most recent call last):
  File "schildbuerger.py", line 2, in <module>
    import stiefo
  File "/home/…/stiefogen/stiefo/__init__.py", line 5, in <module>
    from stiefo.symbols import *
  File "/home/…/stiefogen/stiefo/symbols.py", line 6, in <module>
    from PyQt4 import QtGui, QtCore
ImportError: cannot import name 'QtGui' from 'PyQt4' (unknown location)
```

Is there any hope to solve this in 2020?

**Comment by effjot** [comment]
The code was written by Andreas Hofer. I mainly put it on github, but then development hasn’t proceeded :-(
, probably because I moved on to Aufbauschrift.

I assume you are using Python3. I just tried it on my Debian system and got a similar error. Installing the package `python3-pyqt4` fixed it. I don’t know much about Arch Linux, but there seems to be a package with the same name, so that should be a good starting point.

PyQt4 is a bit old. I’ll try to have a look into moving to PyQt5.

I also just fixed some broken paths in the examples.

**Comment by 4001982248998** [comment]
Thank you very much! After compiling python-pyqt4 and several dependencies, which tool several hours, the program ran. I am happy it works, but probably wouldn't do it again, nor keep this package up to date, so a port to Qt5 would be highly appreciated.

**Comment by effjot** [comment]
I have just ported the program to PyQt5 (commit 46ff71c). It seems to work, but some testing would be good. You can have a look at the `pyqt5` branch.

**Comment by 4001982248998** [comment]
That seems to work wonderfully! :1st_place_medal:

**Comment by effjot** [comment]
Thanks for the feedback!  I have just merged `pyqt5` into `master`.
