### ISSUE TITLE
Set page size

### ISSUE THREAD

**Issue by Protarios** [effjot/stiefogen#2]
Is there a simple possibility to set page size e.g. to a smaller A5 size, to allow compatibility for ebook readers with 6" displays?
Perfect solution of course would be epub export.

**Comment by effjot** [comment]
I’ve implemented a quick solution to changing paper size. Please check out branch `papersize` and tell me it it works for you. An example is in `schildbuerger.py`.

I’m not sure if the PyQt toolkit offers epub export. I think we would need to render to SVG for that. Other people suggested using a different rendering backend altogether. Maybe there are backends that can render Bezier curves directly to epub?

However, the rendering backend is not my top priority right now. First, I need to better understand the parsing and symbol/glyph code (I didn’t write Stiefogen), in order to extend it for Aufbauschrift.

**Comment by Protarios** [comment]
Hi, thank you, the solution works perfect for me.
Looks great on my Tolino and makes reading Stiefo for practise a lot easier.

It is great to hear you are working on Aufbauschrift. 👍

**Comment by effjot** [comment]
I’m glad to know it works on your Tolino!
I had a look into SVG, and generating SVG should be possible without too much trouble. There are at least 2 libraries to generate Epub with Python, and maybe they process SVG.
I’ll keep it on my TODO list. However, completing Aufbauschrift rendering is my priority now.

I just have merged `papersize` into `master`.
