### ISSUE TITLE
Rendering „sich“

### ISSUE THREAD

**Issue by ximarin** [effjot/stiefogen#5]
Let me know if I should stick to english.

Ich lese soeben die Schildbürger PDF und mir fiel auf dass zum Beispiel auf Seite 3, Zeile 8, 2. Wort von rechts, etwas komisch aussieht.
Ich bin aber nicht sicher ob der Fehler bei mir liegt weil ich es falsch gelernt habe.

Bei Wort „sich“ scheint die Tiefstellung nach „s“ eine ganze Stufe zu sein (statt einer halben).
Für „ch“ wird scheinbar der Anfang der oberen Schleife als Fußpunkt verwendet statt des unteren Bogens.

Evtl finde ich was im Code, noch läuft er bei mir nicht.

Gruß und schönes Neues

**Comment by effjot** [comment]
German is ok, as we’re discussing Stiefo-specific. I used English, because the generator might become useful for other systems, too.

Danke, Dir auch ein gutes neues Jahr!

Du hast vermutlich das PDF aus dem `master`-Branch angeschaut. In der Tat ist „sich“ da falsch geschrieben. Auch bei anderen Wörtern mit „-ich“ stimmt es nicht.
In der ursprünglichen Version von Andreas Hofer (commit 37b04ed93) ist es richtig, und auch in meinem aktuellen Entwicklungsbranch `aufbauschrift-2` passt es wieder. Im aktuellen Branch hab ich allerdings noch kein neu erzeugtes PDF commited, Du müsstest es also selber bauen. (Das PDF hier im Repo ist immer noch Andreas Hofers Original.)

Ich hab noch ein paar Tage frei und hoffe, ich kann den Code noch von einem Entwicklunsstand auf was halbwegs stabiles bringen. ;-)

**Comment by effjot** [comment]
Was läuft bei Dir nicht, bzw. was für eine Fehlermeldung kommt? Vielleicht kann ich weiterhelfen.

**Comment by ximarin** [comment]
Ich habe den Fehler gefunden, es lag am Zusammenspiel zwischen PyCharm und Conda... Jetzt läuft der Code für render_on_screen! Da ich noch auf master bin rendert das 'sich' dort natürlich noch falsch.
Welcher Branch wäre der aktuell 'weiteste' der perspektivisch auch master wird?
Das issue würde ich schließen da es ja faktisch kein issue ist.

**Comment by effjot** [comment]
Danke fürs Schließen! Ich hab trotzdem noch reingeschaut – es war ein Fehler, der sich beim Merge mit Andreas Martins `Aufbauschrift-II`-Branch eingeschlichen hatte, weil Andreas bestmmte i-Verbindungen mit einer ganzen Stufe Tiefstellung gemacht hat und ich das nicht ganz verstanden hatte. Im Branch `master` findest Du jetzt den korrigierten Code und das neue PDF.
In meinem aktuellen Branch `aufbauschrift-2` hab ich einige Ansätze von Andreas’ Aufbauschrift 2 schon wieder über den Haufen geworfen. Es sind aber noch nicht alle Aufbauschrift-2-Kürzel fertig. Außerdem habe ich die Branches `pyqt5` und `papersize` noch nicht drin (im `master` sind sie aber schon drin). Ich würde zuerst die Aufbauschrift-2-Kürzel fertigstellen, damit nicht alles durcheinander geht.
